### ISSUE TITLE
Call to undefined method PhpParser\Node\NullableType::toString()

### ISSUE THREAD

**Issue by tomzx** [tomzx/php-semver-checker#94]
```
PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\NullableType::toString() in php-semver-checker-git.phar/vendor/tomzx/php-semver-checker/src/PHPSemVerChecker/Comparator/Type.php:24
Stack trace:
#0 php-semver-checker-git.phar/vendor/tomzx/php-semver-checker/src/PHPSemVerChecker/Comparator/Signature.php(41): PHPSemVerChecker\Comparator\Type::get(Object(PhpParser\Node\NullableType))
#1 php-semver-checker-git.phar/vendor/tomzx/php-semver-checker/src/PHPSemVerChecker/Analyzer/ClassMethodAnalyzer.php(82): PHPSemVerChecker\Comparator\Signature::analyze(Array, Array)
#2 php-semver-checker-git.phar/vendor/tomzx/php-semver-checker/src/PHPSemVerChecker/Analyzer/ClassAnalyzer.php(47): PHPSemVerChecker\Analyzer\ClassMethodAnalyzer->analyze(Object(PhpParser\Node\Stmt\Class_), Object(PhpParser\Node\Stmt\Class_))
#3 php-semver-checker-git.phar/vendor/tomzx/php-semver-checker/src/PHPSemVerChecker/Comparator/Type.php on line 24
```

This error occurs when running against Symfony 4 codebase.

**Comment by tomzx** [comment]
Fixed @ 7bdf3e169b0b9fbbcc670f93c7d25d40db05a223.

**Comment by aivus** [comment]
Hey @tomzx 
Could you please release version with this fix?

**Comment by tomzx** [comment]
@aivus v0.13.0 was pushed with this fix!
